AWSTemplateFormatVersion: '2010-09-09'
Transform: 'AWS::Serverless-2016-10-31'
Description: An AWS Lambda application that integrates Tempus and KTA into the new cloud-hosted Apply service.
Parameters:
  AccountId:
    Type: String
    Default: '754256621582'
    Description: Account ID of the MOJ CP Account
Resources:
  function:
    Type: AWS::Serverless::Function
    Properties:
      Handler: index.handler
      Runtime: nodejs18.x
      CodeUri: function/.
      Description: Call the AWS Lambda API
      Timeout: 30
      # Function's execution role
      Policies:
        # Policies defined inline for AWS Services
        - Statement:
            - Sid: TempusBrokerFunctionQueuePolicy
              Effect: Allow
              Action:
                - sqs:ReceiveMessage
                - sqs:DeleteMessage
                - sqs:GetQueueAttributes
              Resource: '*'
              Condition:
                StringEquals:
                'aws:ResourceAccount': !Ref AccountId
            - Sid: TempusBrokerFunctionS3Policy
              Effect: Allow
              Action:
                - s3:GetObject
                - s3:DeleteObject
              Resource: '*'
              Condition:
                StringEquals:
                'aws:ResourceAccount': !Ref AccountId
            - Sid: TempisBrokerFunctionSSMPolicy
              Effect: Allow
              Action:
                - ssm:GetParameter
              Resource: '*'
              Condition:
                StringEquals:
                'aws:ResourceAccount': !Ref AccountId
        - AWSLambdaBasicExecutionRole
        - AWSLambda_ReadOnlyAccess
        - AWSXrayWriteOnlyAccess
      Tracing: Active
      Layers:
        - !Ref libs
  libs:
    Type: AWS::Serverless::LayerVersion
    Properties:
      LayerName: tempus-broker-nodejs-lib
      Description: Dependencies for the tempus broker function.
      ContentUri: lib/.
      CompatibleRuntimes:
        - nodejs18.x
