AWSTemplateFormatVersion: '2010-09-09'
Transform: 'AWS::Serverless-2016-10-31'
Description: An AWS Lambda application that integrates Tempus and KTA into the new cloud-hosted Apply service.

Parameters:
  MoJCPAccountId:
    Type: String
    Default: '754256621582'
    Description: Account ID of the MOJ CP Account
  Environment:
    Type: String
    Default: dev
    Description: Parameter for the environment
    AllowedValues: ['dev', 'uat', 'stag', 'prod']
  OnPremIpRange:
    Type: String
    Default: '192.168.0.1/16'
    Description: "The CIDR range for CICA's on premise"
  DashboardName:
    Type: String
    Default: TempusBrokerFunctionDashboard
    Description: Unique name for the CloudWatch Dashboard


Mappings:
  EnvironmentMap:
    dev:
      TempusQueueArn: arn:aws:sqs:eu-west-2:754256621582:cica-dev-team-dev-claim-criminal-injuries-tempus-queue
      TempusQueueUrl: https://sqs.eu-west-2.amazonaws.com/754256621582/cica-dev-team-dev-claim-criminal-injuries-tempus-queue
      VpcId: vpc-0e42a25379fa895ec
      SubnetIdA: subnet-02f7ae7f6b1db987f
      SubnetIdB: subnet-0a5e7b48efcb931ba
      TariffSGId: sg-0ebad8b7f67749a6e
      TempusBrokerSecretArn: arn:aws:secretsmanager:eu-west-2:589450497571:secret:tempus-broker-secrets-dev-RC6TNS
    uat:
      TempusQueueArn: arn:aws:sqs:eu-west-2:754256621582:cica-dev-team-uat-claim-criminal-injuries-tempus-queue
      TempusQueueUrl: https://sqs.eu-west-2.amazonaws.com/754256621582/cica-dev-team-uat-claim-criminal-injuries-tempus-queue
      VpcId: vpc-0254c4e3ea99b07d1
      SubnetIdA: subnet-0fd3a560d90368fdc
      SubnetIdB: subnet-078b2047045b77bb0
      TariffSGId: sg-04998e82221c5e57c
      TempusBrokerSecretArn: arn:aws:secretsmanager:eu-west-2:621815915101:secret:tempus-broker-secrets-mFh0th
    stag:
      TempusQueueArn: arn:aws:sqs:eu-west-2:754256621582:cica-staging-claim-criminal-injuries-tempus-queue
      TempusQueueUrl: https://sqs.eu-west-2.amazonaws.com/754256621582/cica-staging-claim-criminal-injuries-tempus-queue
      VpcId: vpc-0e42a25379fa895ec
      SubnetIdA: subnet-02f7ae7f6b1db987f
      SubnetIdB: subnet-0a5e7b48efcb931ba
      TariffSGId: sg-0ebad8b7f67749a6e
      TempusBrokerSecretArn: arn:aws:secretsmanager:eu-west-2:589450497571:secret:tempus-broker-secrets-stag-9wu90l
    prod:
      TempusQueueArn: arn:aws:sqs:eu-west-2:754256621582:cica-dev-team-prod-claim-criminal-injuries-tempus-queue
      TempusQueueUrl: https://sqs.eu-west-2.amazonaws.com/754256621582/cica-dev-team-prod-claim-criminal-injuries-tempus-queue
      VpcId: vpc-010157aa3b29e0752
      SubnetIdA: subnet-0d1fcbfc03a28f433
      SubnetIdB: subnet-08c81bc6ffb13be3d
      TariffSGId: sg-03345c1ce948c936f
      TempusBrokerSecretArn: arn:aws:secretsmanager:eu-west-2:597470279442:secret:tempus-broker-secrets-43bEwb
Resources:
  function:
    Type: AWS::Serverless::Function
    Properties:
      Handler: index.handler
      Runtime: nodejs22.x
      Environment:
        Variables:
          TEMPUS_QUEUE: !FindInMap [EnvironmentMap, !Ref Environment, TempusQueueUrl]
          TEMPUS_BROKER_SECRET_ARN: !FindInMap [EnvironmentMap, !Ref Environment, TempusBrokerSecretArn]
      CodeUri: function/.
      Description: Call the AWS Lambda API
      Timeout: 30
      # Trigger
      Events:
        ScheduleMidnightToSeven: # Covers 00:00 till 19:00
          Type: Schedule
          Properties:
            # Schedule: 'cron(0-59 0-17 ? * * *)' # 00:00 - 17:59 UTC / 01:00 - 18:59 BST
            Schedule: 'cron(0-59 0-18 ? * * *)' # 00:00 - 18:59 GMT
        ScheduleHalfElevenToMidnight: # Covers 11:30 till 00:00
          Type: Schedule
          Properties:
            # Schedule: 'cron(30-59 22 ? * * *)' # 22:30 - 22:59 UTC / 23:30 - 23:59 BST
            Schedule: 'cron(30-59 23 ? * * *)' # 23:30 - 23:59 GMT
        # ScheduleDaylightSavingsHour: # Covers daylight savings discrepancy
            # Third schedule is not needed whilst using GMT
          # Type: Schedule
          # Properties:
            # Schedule: 'cron(0-59 23 ? * * *)' # 23:00 - 23:59 UTC / 00:00 - 01:00 BST
        Schedule24Hour: # Runs every minute of the day - no schedule - disabled by default
          Type: Schedule
          Properties:
            State: DISABLED
            Schedule: rate(1 minute)
        # Function's execution role
      Policies:
        # Policies defined inline for AWS Services
        - Statement:
            - Sid: TempusBrokerFunctionQueuePolicy
              Effect: Allow
              Action:
                - sqs:ReceiveMessage
                - sqs:DeleteMessage
                - sqs:GetQueueAttributes
                - kms:Encrypt
                - kms:Decrypt
                - kms:ReEncrypt*
                - kms:GenerateDataKey*
                - kms:DescribeKey
              Resource: '*'
              Condition:
                StringEquals:
                  'aws:ResourceAccount': !Ref MoJCPAccountId
            - Sid: TempusBrokerFunctionS3Policy
              Effect: Allow
              Action:
                - s3:GetObject
                - s3:DeleteObject
                - kms:Encrypt
                - kms:Decrypt
                - kms:ReEncrypt*
                - kms:GenerateDataKey*
                - kms:DescribeKey
              Resource: '*'
            - Sid: TempusBrokerFunctionSecretsPolicy
              Effect: Allow
              Action:
                - ssm:GetParameter
                - secretsmanager:GetSecretValue
                - kms:Encrypt
                - kms:Decrypt
                - kms:ReEncrypt*
                - kms:GenerateDataKey*
                - kms:DescribeKey
              Resource: '*'
            - Sid: TempusBrokerFunctionCloudWatchPolicy
              Effect: Allow
              Action:
                  - cloudwatch:PutMetricData
              Resource: '*'
            - Sid: CloudWatchDashboardPolicy
              Effect: Allow
              Action:
                  - cloudwatch:PutDashboard
                  - cloudwatch:GetDashboard
                  - cloudwatch:ListDashboards
                  - cloudwatch:DeleteDashboards
              Resource: "*"
        - AWSLambdaBasicExecutionRole
        - AWSLambda_ReadOnlyAccess
        - AWSXrayWriteOnlyAccess
      Tracing: Active
      Layers:
        - !Ref libs
      VpcConfig:
        SubnetIds:
          [
            !FindInMap [EnvironmentMap, !Ref Environment, SubnetIdA],
            !FindInMap [EnvironmentMap, !Ref Environment, SubnetIdB],
          ]
        SecurityGroupIds: [!Ref tempusBrokerSecurityGroup]
  libs:
    Type: AWS::Serverless::LayerVersion
    Properties:
      LayerName: tempus-broker-nodejs-lib
      Description: Dependencies for the tempus broker function.
      ContentUri: lib/.
      CompatibleRuntimes:
        - nodejs22.x
  tempusBrokerSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupName: !Sub
        - 'TempusBrokerSecurityGroup${Env}'
        - Env: !Ref Environment
      GroupDescription: Security group for the tempus broker lamdba function to allow communications out to Tariff and Tempus.
      VpcId: !FindInMap [EnvironmentMap, !Ref Environment, VpcId]
      SecurityGroupEgress:
        - IpProtocol: tcp
          FromPort: 1521
          ToPort: 1521
          DestinationSecurityGroupId: !FindInMap [EnvironmentMap, !Ref Environment, TariffSGId]
        - IpProtocol: tcp
          FromPort: 443
          ToPort: 443
          CidrIp: !Ref OnPremIpRange
        - IpProtocol: tcp
          FromPort: 0
          ToPort: 65535
          CidrIp: '0.0.0.0/0'
  TempusBrokerDashboard:
    Type: AWS::CloudWatch::Dashboard
    Properties:
      DashboardName: !Ref DashboardName
      DashboardBody:
        Fn::Sub: |
          {
            "widgets": [
              {
                "type": "metric",
                "x": 0,
                "y": 0,
                "width": 6,
                "height": 6,
                "properties": {
                  "metrics": [
                    [ "tempusBrokerFunction/requests", "ktaRequestLatency", "ktaRequestUrl", "ALL" ]
                  ],
                  "view": "gauge",
                  "stat": "p50",
                  "region": "${AWS::Region}",
                  "title": "KTA Request Latency (Average)",
                  "yAxis": {
                    "left": {
                      "min": 0,
                      "max": 1000
                    }
                  }
                }
              }
            ]
          }
