on:
  push:
    branches: 
      - main
    paths-ignore:
      - '**/*.md'
      - '**/LICENSE'
      - '**/.gitignore'

  # Allow manual triggering of the workflow
  workflow_dispatch:

jobs:
  build-deploy:
    runs-on: ubuntu-latest
    environment:
      name: prod
    permissions:
      id-token: write
      contents: read
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.13.3'
      - uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: 'npm'
      - uses: aws-actions/setup-sam@v2
        with:
          use-installer: true
      - uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ secrets.AWS_ROLE_TO_ASSUME }}
          role-session-name: GitHubWorkflow
          aws-region: eu-west-2

      # assume the relevant role via AWS Profile
      - run: sh ./.github/scripts/assume-role-profile.sh
        env:
          ROLE_ARN: ${{ secrets.ASSUMED_ROLE }}

      # install dependencies into a lambda layer
      - run: sh ./.github/scripts/build-layer.sh

      # sam build
      - run: sam build --use-container

      # deploy
      - run: sam deploy --no-confirm-changeset --no-fail-on-empty-changeset --stack-name tempus-broker --resolve-s3 --capabilities CAPABILITY_IAM --region eu-west-2 --profile assumed-role --parameter-overrides DashboardName=TempusBrokerFunctionDashboard-prod Environment=prod
